feat: more tidying

diff --git a/files/dotfiles/_bash_completions b/files/dotfiles/_bash_completions
--- a/files/dotfiles/_bash_completions
+++ b/files/dotfiles/_bash_completions
@@ -1,14 +1,17 @@
-#!/usr/bin/env bash
-
 ### test for tools that I use a lot and add their shell completions or give warnings where they can't be found
 
-hash helm 2> /dev/null && source <(helm completion bash) || \
-  echo "[INFO]: Couldn't find helm on PATH"
-hash kubectl 2> /dev/null && source <(kubectl completion bash) || \
-  echo "[INFO]: Couldn't find kubectl on PATH"
-hash kustomize 2> /dev/null && source <(kustomize completion bash) || \
-  echo "[INFO]: Couldn't find kustomize on PATH"
-hash op 2> /dev/null && source <(op completion bash) || \
-  echo "[INFO]: Couldn't find op on PATH"
-hash terraform 2> /dev/null && complete -C terraform terraform || \
-  echo "[INFO]: Couldn't find terraform on PATH"
+hash helm 2> /dev/null \
+  && source <(helm completion bash) \
+  || echo "[INFO]: Couldn't find helm on PATH"
+hash kubectl 2> /dev/null \
+  && source <(kubectl completion bash) \
+  || echo "[INFO]: Couldn't find kubectl on PATH"
+hash kustomize 2> /dev/null \
+  && source <(kustomize completion bash) \
+  || echo "[INFO]: Couldn't find kustomize on PATH"
+hash op 2> /dev/null \
+  && source <(op completion bash) \
+  || echo "[INFO]: Couldn't find op on PATH"
+hash terraform 2> /dev/null \
+  && complete -C terraform terraform \
+  || echo "[INFO]: Couldn't find terraform on PATH"
diff --git a/files/dotfiles/_bash_exports b/files/dotfiles/_bash_exports
--- a/files/dotfiles/_bash_exports
+++ b/files/dotfiles/_bash_exports
@@ -1,5 +1,3 @@
-#!/bin/bash
-
 export LC_ALL=en_GB.UTF-8
 
 # more colours in terminal
@@ -20,12 +18,15 @@ export PROMPT_COMMAND="history -n; history -w; history -c; history -r; $PROMPT_C
 export HISTIGNORE="ls:cd:cd -:pwd:exit:date:* --help:* help:* --version";
 
 # local scripts
-[[ -d "${HOME}/bin" ]] && pathprepend ${HOME}/bin || \
-  echo 'No bindir found at '${HOME}/bin'. Not adding to $PATH.'
+[[ -d "${HOME}/bin" ]] \
+  && pathprepend ${HOME}/bin \
+  || echo 'No bindir found at '${HOME}/bin'. Not adding to $PATH.'
 
 # golang exports
-[[ -f "/usr/local/go/bin/go" ]] && export GOROOT="/usr/local/go" && \
-  pathappend ${GOROOT}/bin || echo "GOROOT not set. Is Go installed?"
+[[ -f "/usr/local/go/bin/go" ]] \
+  && export GOROOT="/usr/local/go" \
+  && pathappend ${GOROOT}/bin \
+  || echo "GOROOT not set. Is Go installed?"
 
 set_go_path() {
 local mygopath="${HOME}/go"
@@ -40,8 +41,9 @@ fi
 
 set_go_path
 
-[[ -d "${GOPATH}/bin" ]] && pathappend ${GOPATH}/bin || \
-  echo 'Go bindir not found at '${GOPATH}/bin'. Not adding to $PATH.'
+[[ -d "${GOPATH}/bin" ]] \
+  && pathappend ${GOPATH}/bin \
+  || echo 'Go bindir not found at '${GOPATH}/bin'. Not adding to $PATH.'
 
 # mvn exports
 export MAVEN_HOME="${HOME}/bin/apache-maven-3.6.3"
@@ -56,7 +58,9 @@ pathappend ${MAVEN_HOME}/bin
 #  echo 'nvm not found in '${HOME}'. Not setting $NVM_DIR.'
 
 # my git dir
-[[ -d "${HOME}/mygit" ]] && export MY_GIT_DIR="${HOME}/mygit"
+[[ -d "${HOME}/mygit" ]] \
+  && export MY_GIT_DIR="${HOME}/mygit" \
+  || echo "Create your mygit dir!"
 
 # trim dir for bash_prompt
 [[ "${BASH_VERSINFO[0]}" -lt 4 ]] || export PROMPT_DIRTRIM=3
@@ -68,8 +72,7 @@ export PASSWORD_STORE_ENABLE_EXTENSIONS=true
 export AWS_SDK_LOAD_CONFIG=1
 
 [[ -d "${HOME}/.krew/bin" ]] && pathappend ${HOME}/.krew/bin
-
-[[ -d "${HOME}/.local/bin" ]] && pathappend ${HOME}/.local/bin
+[[ -d "${HOME}/.local/bin" ]] && pathprepend ${HOME}/.local/bin
 
 export XDG_CONFIG_HOME=${HOME}/.config
 export XDG_CACHE_HOME=${HOME}/.cache
diff --git a/files/dotfiles/_bash_profile b/files/dotfiles/_bash_profile
--- a/files/dotfiles/_bash_profile
+++ b/files/dotfiles/_bash_profile
@@ -1,30 +1,37 @@
-#!/bin/bash
-
 #bash environment
 shopt -s extglob;
 shopt -s histappend;
 
 #Load in local config values
-[[ -r ~/.my_local_config ]] && source ~/.my_local_config \
+[[ -r "${HOME}/.my_local_config" ]] \
+  && source "${HOME}/.my_local_config" \
   || echo "no local config found. skipping"
 
 #Load in our dotfiles
-for file in ~/.{bash_aliases,bash_functions,bash_exports,bash_prompt,bash_completions}; do
-  [[ -r "$file" ]] && [[ -f "$file" ]] && source "$file" || \
-  echo "Could not source ${file}. What up?!"
+for file in "${HOME}"/.{bash_aliases,bash_functions,bash_exports,bash_prompt,bash_completions}; do
+  [[ -r "$file" ]] \
+  && [[ -f "$file" ]] \
+  && source "$file" \
+  || echo "Could not source ${file}. What up?!"
 done
 
 # source specific files and functions
-[[ -n "${NPM_DEV}" ]] && source ~/.bash_npm_config
-[[ -n "${RUBY_DEV}" ]] && source ~/.bash_ruby_config
+[[ -n "${NPM_DEV}" ]] \
+  && source "${HOME}/.bash_npm_config" \
+  || true
+
+[[ -n "${RUBY_DEV}" ]] \
+  && source "${HOME}/.bash_ruby_config" \
+  || true
 
 # check if we're in WSL and import ssh key to keychain
-[[ -v WSLENV ]] && hash keychain 2> /dev/null && eval $(keychain --eval --agents ssh id_ed25519) || echo "[INFO]: not a WSL environment"
+[[ -v WSLENV ]] \
+  && hash keychain 2> /dev/null \
+  && eval "$(keychain --eval --agents ssh id_ed25519)" \
+  || echo "[INFO]: not a WSL environment"
 
-[[ -f /usr/local/etc/bash_completion ]] && \
-  source /usr/local/etc/bash_completion
+# if [ -e /home/amo/.nix-profile/etc/profile.d/nix.sh ]; then . /home/amo/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
 
-if [ -e /home/amo/.nix-profile/etc/profile.d/nix.sh ]; then . /home/amo/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
-
-export PATH="$HOME/.cargo/bin:$PATH"
-[[ -d "$HOME/.local/bin" ]] && export PATH="$HOME/.local/bin:$PATH"
+[[ -d "$HOME/.cargo/bin" ]] \
+  && export PATH="$HOME/.cargo/bin:$PATH" \
+  || echo "cargo package dir not found"
